crnk:
  enabled: true
  path-prefix: "/api"
  default-page-limit: 20
  max-page-limit: 1000
  allow-unknown-attributes: false
  return404-on-null: true
server:
  port: 8082
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/tasks"
    username: "postgres"
    password: "mysecretpassword"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: "org.hibernate.dialect.PostgreSQL9Dialect"
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
